version: "3"
services:

  documentation:
    image: "${IMAGE:-node:9-stretch}"
    ports:
      - 80:8080

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - 8080:8080

  contracts:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../contracts:/www/data
